# Generated by Django 5.2.4 on 2025-11-06 13:30
# Modified to handle existing Oracle tables and indexes gracefully

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_table_exists(cursor, table_name):
    """Check if a table exists in Oracle database"""
    try:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM user_tables 
            WHERE table_name = UPPER(%s)
        """, [table_name])
        return cursor.fetchone()[0] > 0
    except Exception:
        return False


def check_column_exists(cursor, table_name, column_name):
    """Check if a column exists in a table in Oracle database"""
    try:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM user_tab_columns 
            WHERE table_name = UPPER(%s) AND column_name = UPPER(%s)
        """, [table_name, column_name])
        return cursor.fetchone()[0] > 0
    except Exception:
        return False


def check_constraint_exists(cursor, constraint_name):
    """Check if a constraint exists in Oracle database"""
    try:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM user_constraints 
            WHERE constraint_name = UPPER(%s)
        """, [constraint_name])
        return cursor.fetchone()[0] > 0
    except Exception:
        return False


def check_index_exists(cursor, index_name):
    """Check if an index exists in Oracle database"""
    try:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM user_indexes 
            WHERE index_name = UPPER(%s)
        """, [index_name])
        return cursor.fetchone()[0] > 0
    except Exception:
        return False


class SafeCreateModel(migrations.CreateModel):
    """
    Custom CreateModel that handles existing tables in Oracle.
    If table exists, it will try to add any missing columns from the model definition.
    """
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'oracle':
            model = to_state.apps.get_model(app_label, self.name)
            # Check if table exists before creating
            with schema_editor.connection.cursor() as cursor:
                if not check_table_exists(cursor, model._meta.db_table):
                    # Table doesn't exist - create it normally
                    super().database_forwards(app_label, schema_editor, from_state, to_state)
                else:
                    # Table exists - check and add missing columns
                    print(f"Table {model._meta.db_table} already exists, checking for missing columns...")
                    for field in model._meta.local_fields:
                        column_name = field.column
                        if not check_column_exists(cursor, model._meta.db_table, column_name):
                            print(f"  Adding missing column: {column_name}")
                            try:
                                schema_editor.add_field(model, field)
                            except Exception as e:
                                print(f"  Warning: Could not add column {column_name}: {e}")
                        else:
                            print(f"  Column {column_name} already exists")
        else:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class SafeAddField(migrations.AddField):
    """Custom AddField that skips if column already exists in Oracle"""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'oracle':
            to_model = to_state.apps.get_model(app_label, self.model_name)
            # Get the actual field to determine column name
            field = to_model._meta.get_field(self.name)
            column_name = field.column if hasattr(field, 'column') else self.name
            # Check if column exists before adding
            with schema_editor.connection.cursor() as cursor:
                if not check_column_exists(cursor, to_model._meta.db_table, column_name):
                    super().database_forwards(app_label, schema_editor, from_state, to_state)
                else:
                    # Skip existing column silently
                    pass
        else:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class SafeAlterUniqueTogether(migrations.AlterUniqueTogether):
    """Custom AlterUniqueTogether that skips if constraints already exist in Oracle"""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'oracle':
            # Try to apply, but catch the specific error for existing constraints
            try:
                super().database_forwards(app_label, schema_editor, from_state, to_state)
            except Exception as e:
                # If constraint already exists, skip silently
                if 'ORA-02261' in str(e) or 'already exists' in str(e).lower():
                    pass
                else:
                    raise
        else:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class SafeAddIndex(migrations.AddIndex):
    """Custom AddIndex that skips if index already exists in Oracle"""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'oracle':
            # Check if index exists before creating
            with schema_editor.connection.cursor() as cursor:
                if not check_index_exists(cursor, self.index.name):
                    super().database_forwards(app_label, schema_editor, from_state, to_state)
                else:
                    # Skip existing index silently
                    pass
        else:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        SafeCreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center_code', models.CharField(db_index=True, help_text='Unique identifier (e.g., CC-001)', max_length=50, unique=True, verbose_name='Cost Center Code')),
                ('cost_center_code_hash', models.CharField(db_index=True, editable=False, help_text='SHA256 hash for database-portable queries', max_length=64)),
                ('cost_center_name', models.CharField(max_length=255, verbose_name='Cost Center Name')),
                ('cost_center_name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center Name (Arabic)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description (Arabic)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('manager_email', models.EmailField(blank=True, help_text='Manager email for CC field', max_length=255, null=True, verbose_name='Manager Email')),
                ('common_email', models.TextField(blank=True, help_text='Comma-separated CC emails', null=True, verbose_name='Common CC Emails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cost_centers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('users', models.ManyToManyField(blank=True, help_text='Users who will receive emails (TO field)', related_name='cost_centers', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'db_table': 'email_costcenter',
                'ordering': ['cost_center_code'],
            },
        ),
        SafeCreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement (All Cost Centers)'), ('SPECIFIC', 'Specific Cost Centers')], max_length=20, verbose_name='Send Type')),
                ('subject', models.CharField(max_length=500, verbose_name='Email Subject')),
                ('body_html', models.TextField(verbose_name='Email Body (HTML)')),
                ('cost_center_ids', models.TextField(blank=True, help_text='Comma-separated IDs for SPECIFIC send type', null=True, verbose_name='Cost Center IDs')),
                ('draft_name', models.CharField(blank=True, help_text='Optional name for organizing drafts', max_length=255, null=True, verbose_name='Draft Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag', verbose_name='Is Deleted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Draft Owner')),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'db_table': 'email_draft',
                'ordering': ['-updated_at'],
            },
        ),
        SafeCreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('SPECIFIC', 'Specific Cost Centers')], db_index=True, max_length=20, verbose_name='Send Type')),
                ('email_type', models.CharField(choices=[('SENT', 'Sent Email'), ('RECEIVED', 'Received Email')], db_index=True, help_text='SENT for outbox, RECEIVED for inbox', max_length=20, verbose_name='Email Type')),
                ('subject', models.CharField(max_length=500, verbose_name='Email Subject')),
                ('body_html', models.TextField(verbose_name='Email Body (HTML)')),
                ('recipient_emails', models.TextField(help_text='Comma-separated TO emails', verbose_name='Recipient Emails (TO)')),
                ('cc_emails', models.TextField(blank=True, help_text='Comma-separated CC emails', null=True, verbose_name='CC Emails')),
                ('email_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=20, verbose_name='Email Status')),
                ('email_error', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sent At')),
                ('metadata', models.TextField(blank=True, help_text='Additional data as JSON string', null=True, verbose_name='Metadata (JSON)')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='email_communication.costcenter', verbose_name='Cost Center')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='email_communication.emaildraft', verbose_name='Draft Sent From')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_log',
                'ordering': ['-sent_at'],
            },
        ),
        SafeCreateModel(
            name='EmailRecipientView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_to', models.BooleanField(default=True, help_text='True if in TO field, False if in CC', verbose_name='Is TO Recipient')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_starred', models.BooleanField(db_index=True, default=False, verbose_name='Is Starred')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Is Archived')),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_views', to='email_communication.emaillog', verbose_name='Email Log')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to=settings.AUTH_USER_MODEL, verbose_name='Recipient User')),
            ],
            options={
                'verbose_name': 'Email Recipient View',
                'verbose_name_plural': 'Email Recipient Views',
                'db_table': 'email_recipient_view',
                'ordering': ['-email_log__sent_at'],
            },
        ),
        SafeCreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Template Name')),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Template Name (Arabic)')),
                ('subject', models.CharField(help_text='Users can edit before sending', max_length=500, verbose_name='Default Subject')),
                ('subject_ar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Default Subject (Arabic)')),
                ('body_html', models.TextField(help_text='Users can edit before sending', verbose_name='Default HTML Body')),
                ('body_html_ar', models.TextField(blank=True, null=True, verbose_name='Default HTML Body (Arabic)')),
                ('body_text', models.TextField(blank=True, help_text='Auto-generated fallback', null=True, verbose_name='Plain Text Body')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active templates shown to users', verbose_name='Is Active')),
                ('category', models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('update', 'Update'), ('notification', 'Notification'), ('report', 'Report'), ('meeting', 'Meeting'), ('other', 'Other')], db_index=True, max_length=100, null=True, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_template',
                'ordering': ['-created_at'],
            },
        ),
        SafeAddField(
            model_name='emaillog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='email_communication.emailtemplate', verbose_name='Template Used'),
        ),
        SafeAddField(
            model_name='emaildraft',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='email_communication.emailtemplate', verbose_name='Template Used'),
        ),
        SafeAddIndex(
            model_name='costcenter',
            index=models.Index(fields=['cost_center_code_hash'], name='idx_cc_code_hash'),
        ),
        SafeAddIndex(
            model_name='costcenter',
            index=models.Index(fields=['is_active'], name='idx_cc_active'),
        ),
        SafeAddIndex(
            model_name='emailrecipientview',
            index=models.Index(fields=['recipient_user', 'is_read'], name='idx_recip_user_read'),
        ),
        SafeAddIndex(
            model_name='emailrecipientview',
            index=models.Index(fields=['recipient_user', 'is_starred'], name='idx_recip_user_star'),
        ),
        SafeAddIndex(
            model_name='emailrecipientview',
            index=models.Index(fields=['recipient_user', 'is_archived'], name='idx_recip_user_arch'),
        ),
        SafeAlterUniqueTogether(
            name='emailrecipientview',
            unique_together={('email_log', 'recipient_user')},
        ),
        SafeAddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['is_active'], name='idx_tmpl_active'),
        ),
        SafeAddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['category'], name='idx_tmpl_category'),
        ),
        SafeAddIndex(
            model_name='emaillog',
            index=models.Index(fields=['user', 'email_type'], name='idx_log_user_type'),
        ),
        SafeAddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_status'], name='idx_log_status'),
        ),
        SafeAddIndex(
            model_name='emaillog',
            index=models.Index(fields=['sent_at'], name='idx_log_sent_at'),
        ),
        SafeAddIndex(
            model_name='emaillog',
            index=models.Index(fields=['cost_center'], name='idx_log_cc'),
        ),
        SafeAddIndex(
            model_name='emaildraft',
            index=models.Index(fields=['user', 'is_deleted'], name='idx_draft_user_del'),
        ),
        SafeAddIndex(
            model_name='emaildraft',
            index=models.Index(fields=['created_at'], name='idx_draft_created'),
        ),
    ]
