# Generated by Django 5.2.4 on 2025-11-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center_code', models.CharField(db_index=True, help_text='Unique identifier (e.g., CC-001)', max_length=50, unique=True, verbose_name='Cost Center Code')),
                ('cost_center_code_hash', models.CharField(db_index=True, editable=False, help_text='SHA256 hash for database-portable queries', max_length=64)),
                ('cost_center_name', models.CharField(max_length=255, verbose_name='Cost Center Name')),
                ('cost_center_name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center Name (Arabic)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description (Arabic)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('manager_email', models.EmailField(blank=True, help_text='Manager email for CC field', max_length=255, null=True, verbose_name='Manager Email')),
                ('common_email', models.TextField(blank=True, help_text='Comma-separated CC emails', null=True, verbose_name='Common CC Emails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cost_centers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('users', models.ManyToManyField(blank=True, help_text='Users who will receive emails (TO field)', related_name='cost_centers', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'db_table': 'email_costcenter',
                'ordering': ['cost_center_code'],
            },
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement (All Cost Centers)'), ('SPECIFIC', 'Specific Cost Centers')], max_length=20, verbose_name='Send Type')),
                ('subject', models.CharField(max_length=500, verbose_name='Email Subject')),
                ('body_html', models.TextField(verbose_name='Email Body (HTML)')),
                ('cost_center_ids', models.TextField(blank=True, help_text='Comma-separated IDs for SPECIFIC send type', null=True, verbose_name='Cost Center IDs')),
                ('draft_name', models.CharField(blank=True, help_text='Optional name for organizing drafts', max_length=255, null=True, verbose_name='Draft Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag', verbose_name='Is Deleted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Draft Owner')),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'db_table': 'email_draft',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('SPECIFIC', 'Specific Cost Centers')], db_index=True, max_length=20, verbose_name='Send Type')),
                ('email_type', models.CharField(choices=[('SENT', 'Sent Email'), ('RECEIVED', 'Received Email')], db_index=True, help_text='SENT for outbox, RECEIVED for inbox', max_length=20, verbose_name='Email Type')),
                ('subject', models.CharField(max_length=500, verbose_name='Email Subject')),
                ('body_html', models.TextField(verbose_name='Email Body (HTML)')),
                ('recipient_emails', models.TextField(help_text='Comma-separated TO emails', verbose_name='Recipient Emails (TO)')),
                ('cc_emails', models.TextField(blank=True, help_text='Comma-separated CC emails', null=True, verbose_name='CC Emails')),
                ('email_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=20, verbose_name='Email Status')),
                ('email_error', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sent At')),
                ('metadata', models.TextField(blank=True, help_text='Additional data as JSON string', null=True, verbose_name='Metadata (JSON)')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='email_communication.costcenter', verbose_name='Cost Center')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='email_communication.emaildraft', verbose_name='Draft Sent From')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecipientView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_to', models.BooleanField(default=True, help_text='True if in TO field, False if in CC', verbose_name='Is TO Recipient')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_starred', models.BooleanField(db_index=True, default=False, verbose_name='Is Starred')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Is Archived')),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_views', to='email_communication.emaillog', verbose_name='Email Log')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to=settings.AUTH_USER_MODEL, verbose_name='Recipient User')),
            ],
            options={
                'verbose_name': 'Email Recipient View',
                'verbose_name_plural': 'Email Recipient Views',
                'db_table': 'email_recipient_view',
                'ordering': ['-email_log__sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Template Name')),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Template Name (Arabic)')),
                ('subject', models.CharField(help_text='Users can edit before sending', max_length=500, verbose_name='Default Subject')),
                ('subject_ar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Default Subject (Arabic)')),
                ('body_html', models.TextField(help_text='Users can edit before sending', verbose_name='Default HTML Body')),
                ('body_html_ar', models.TextField(blank=True, null=True, verbose_name='Default HTML Body (Arabic)')),
                ('body_text', models.TextField(blank=True, help_text='Auto-generated fallback', null=True, verbose_name='Plain Text Body')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active templates shown to users', verbose_name='Is Active')),
                ('category', models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('update', 'Update'), ('notification', 'Notification'), ('report', 'Report'), ('meeting', 'Meeting'), ('other', 'Other')], db_index=True, max_length=100, null=True, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='email_communication.emailtemplate', verbose_name='Template Used'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='email_communication.emailtemplate', verbose_name='Template Used'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['cost_center_code_hash'], name='idx_cc_code_hash'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['is_active'], name='idx_cc_active'),
        ),
        migrations.AddIndex(
            model_name='emailrecipientview',
            index=models.Index(fields=['recipient_user', 'is_read'], name='idx_recip_user_read'),
        ),
        migrations.AddIndex(
            model_name='emailrecipientview',
            index=models.Index(fields=['recipient_user', 'is_starred'], name='idx_recip_user_star'),
        ),
        migrations.AddIndex(
            model_name='emailrecipientview',
            index=models.Index(fields=['recipient_user', 'is_archived'], name='idx_recip_user_arch'),
        ),
        migrations.AlterUniqueTogether(
            name='emailrecipientview',
            unique_together={('email_log', 'recipient_user')},
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['is_active'], name='idx_tmpl_active'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['category'], name='idx_tmpl_category'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['user', 'email_type'], name='idx_log_user_type'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_status'], name='idx_log_status'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['sent_at'], name='idx_log_sent_at'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['cost_center'], name='idx_log_cc'),
        ),
        migrations.AddIndex(
            model_name='emaildraft',
            index=models.Index(fields=['user', 'is_deleted'], name='idx_draft_user_del'),
        ),
        migrations.AddIndex(
            model_name='emaildraft',
            index=models.Index(fields=['created_at'], name='idx_draft_created'),
        ),
    ]
