# Generated by Django 5.2.4 on 2025-11-06 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcenter',
            name='common_email',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='manager_email',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='users',
        ),
        migrations.CreateModel(
            name='CostCenterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('email_hash', models.CharField(db_index=True, editable=False, help_text='SHA256 hash for database-portable queries', max_length=64)),
                ('email_type', models.CharField(choices=[('recipient', 'Recipient (TO)'), ('cc', 'CC (Carbon Copy)')], db_index=True, help_text='Type of email: recipient (TO) or cc', max_length=20, verbose_name='Email Type')),
                ('display_name', models.CharField(blank=True, help_text='Optional display name for the email', max_length=255, null=True, verbose_name='Display Name')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_communication.costcenter', verbose_name='Cost Center')),
            ],
            options={
                'verbose_name': 'Cost Center Email',
                'verbose_name_plural': 'Cost Center Emails',
                'db_table': 'email_costcenter_email',
                'ordering': ['email_type', 'email'],
                'indexes': [models.Index(fields=['email_hash'], name='idx_cc_email_hash'), models.Index(fields=['email_type'], name='idx_cc_email_type'), models.Index(fields=['cost_center', 'email_type'], name='idx_cc_emailtype')],
                'unique_together': {('cost_center', 'email', 'email_type')},
            },
        ),
    ]
