# Generated by Django 5.2.4 on 2025-11-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_communication', '0002_remove_costcenter_common_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('NOTIFICATION', 'Notification'), ('REMINDER', 'Reminder'), ('REPORT', 'Report'), ('OTHER', 'Other')], db_index=True, max_length=100, null=True, verbose_name='Category'),
        ),
    ]
