# Generated by Django 5.2.4 on 2026-06-16 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_communication', '0003_alter_emailtemplate_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_data', models.BinaryField(help_text='File content stored as BLOB (max 15MB)')),
                ('original_filename', models.CharField(help_text='Sanitized original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='Validated MIME type', max_length=150)),
                ('description', models.CharField(blank=True, help_text='Optional description of the attachment', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('draft', models.ForeignKey(blank=True, help_text='Owning draft (if attached to a draft)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_communication.emaildraft')),
                ('sent_log', models.ForeignKey(blank=True, help_text='Owning sent email log (immutable sent copy)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_attachments', to='email_communication.emaillog')),
                ('template', models.ForeignKey(blank=True, help_text='Owning template (if attached to a template)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_communication.emailtemplate')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_email_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'db_table': 'email_attachment',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLogAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_links', to='email_communication.emailattachment', verbose_name='Attachment')),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='email_communication.emaillog', verbose_name='Email Log')),
            ],
            options={
                'verbose_name': 'Email Log Attachment',
                'verbose_name_plural': 'Email Log Attachments',
                'db_table': 'email_log_attachment',
            },
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['template'], name='idx_email_att_tmpl'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['draft'], name='idx_email_att_draft'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['sent_log'], name='idx_email_att_log'),
        ),
        migrations.AddIndex(
            model_name='emaillogattachment',
            index=models.Index(fields=['email_log'], name='idx_logatt_log'),
        ),
        migrations.AlterUniqueTogether(
            name='emaillogattachment',
            unique_together={('email_log', 'attachment')},
        ),
    ]
