# Generated by Django 5.2.4 on 2026-06-16 09:35
# Rewritten to be idempotent for Oracle:
#   - Uses SeparateDatabaseAndState so Django's model registry is always updated
#     even when the tables already exist in the database.
#   - Uses _RunPythonWithToState (a RunPython subclass) so that the callback
#     receives to_state.apps — the state AFTER state_operations are applied —
#     making apps.get_model('EmailAttachment') available even though the model
#     is created by this same migration.
#   - Silently ignores ORA-00955 (name already used), ORA-01408 (column already
#     indexed), and ORA-02261 (unique key already exists) so the migration
#     succeeds on both fresh schemas and databases where these tables were
#     created by a previous hand-written migration.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# ── Oracle "already exists" error codes ──────────────────────────────────────
_ORA_ALREADY_EXISTS = frozenset(['00955', '01408', '02261'])


def _already_exists(exc):
    """True when the DatabaseError means the object already exists in Oracle."""
    s = str(exc)
    return any(code in s for code in _ORA_ALREADY_EXISTS)


# ── Custom RunPython that forwards to_state.apps ──────────────────────────────

class _RunPythonWithToState(migrations.RunPython):
    """
    Variant of RunPython that passes to_state.apps to the *forward* callback
    instead of from_state.apps.

    This is required inside SeparateDatabaseAndState: the state_operations
    update the model registry only in to_state, so a normal RunPython's
    callback would receive a from_state that has no knowledge of models created
    by those same state_operations (e.g. EmailAttachment in this migration).
    Using to_state.apps fixes the KeyError / LookupError at runtime.

    The *reverse* callback still receives from_state.apps because when rolling
    back, from_state is the post-migration state where the models DO exist.
    """

    def database_forwards(self, _app_label, schema_editor, _from_state, to_state):
        if self.atomic:
            from django.db import transaction
            with transaction.atomic(using=schema_editor.connection.alias):
                self.code(to_state.apps, schema_editor)
        else:
            self.code(to_state.apps, schema_editor)

    def database_backwards(self, _app_label, schema_editor, from_state, _to_state):
        if self.reverse_code is None:
            raise NotImplementedError(
                "Reverse migration requires a reverse_code function."
            )
        if self.atomic:
            from django.db import transaction
            with transaction.atomic(using=schema_editor.connection.alias):
                self.reverse_code(from_state.apps, schema_editor)
        else:
            self.reverse_code(from_state.apps, schema_editor)


# ── Forward migration ─────────────────────────────────────────────────────────

def _create_tables_idempotent(apps, schema_editor):
    """
    Create EmailAttachment and EmailLogAttachment — idempotent.

    If a table already exists (ORA-00955) the CREATE is skipped and we instead
    verify that each required index / unique constraint is present, silently
    ignoring any that already exist.
    """
    from django.db.utils import DatabaseError

    EmailAttachment = apps.get_model('email_communication', 'EmailAttachment')
    EmailLogAttachment = apps.get_model('email_communication', 'EmailLogAttachment')

    # ── EmailAttachment ───────────────────────────────────────────────────────
    created_fresh = False
    try:
        schema_editor.create_model(EmailAttachment)
        created_fresh = True
    except DatabaseError as exc:
        if not _already_exists(exc):
            raise

    if not created_fresh:
        # Table already present — ensure every declared index exists.
        for idx in EmailAttachment._meta.indexes:
            try:
                schema_editor.add_index(EmailAttachment, idx)
            except DatabaseError as exc:
                if not _already_exists(exc):
                    raise

    # ── EmailLogAttachment ────────────────────────────────────────────────────
    created_fresh = False
    try:
        schema_editor.create_model(EmailLogAttachment)
        created_fresh = True
    except DatabaseError as exc:
        if not _already_exists(exc):
            raise

    if not created_fresh:
        for idx in EmailLogAttachment._meta.indexes:
            try:
                schema_editor.add_index(EmailLogAttachment, idx)
            except DatabaseError as exc:
                if not _already_exists(exc):
                    raise

        # Ensure unique_together (email_log, attachment).
        try:
            schema_editor.alter_unique_together(
                EmailLogAttachment,
                old_unique_together=set(),
                new_unique_together={('email_log', 'attachment')},
            )
        except DatabaseError as exc:
            if not _already_exists(exc):
                raise


# ── Reverse migration ─────────────────────────────────────────────────────────

def _drop_tables(apps, schema_editor):
    """Drop both tables; ignore ORA-00942 (table does not exist)."""
    from django.db.utils import DatabaseError

    for model_name in ('EmailLogAttachment', 'EmailAttachment'):
        model = apps.get_model('email_communication', model_name)
        try:
            schema_editor.delete_model(model)
        except DatabaseError as exc:
            if 'ORA-00942' not in str(exc) and '00942' not in str(exc):
                raise


# ── Migration class ───────────────────────────────────────────────────────────

class Migration(migrations.Migration):

    # Oracle DDL auto-commits; wrapping in a transaction block is a no-op at best
    # and confusing at worst.
    atomic = False

    dependencies = [
        ('email_communication', '0003_alter_emailtemplate_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # ----------------------------------------------------------------
            # state_operations — only update Django's in-memory model registry.
            # These never touch the database.  They give to_state.apps the
            # EmailAttachment / EmailLogAttachment models that the RunPython
            # callback (below) needs to call schema_editor.create_model().
            # ----------------------------------------------------------------
            state_operations=[
                migrations.CreateModel(
                    name='EmailAttachment',
                    fields=[
                        ('id', models.UUIDField(
                            default=uuid.uuid4, editable=False,
                            primary_key=True, serialize=False,
                        )),
                        ('file_data', models.BinaryField(
                            help_text='File content stored as BLOB (max 15MB)',
                        )),
                        ('original_filename', models.CharField(
                            help_text='Sanitized original filename',
                            max_length=255,
                        )),
                        ('file_size', models.IntegerField(
                            help_text='File size in bytes',
                        )),
                        ('mime_type', models.CharField(
                            help_text='Validated MIME type',
                            max_length=150,
                        )),
                        ('description', models.CharField(
                            blank=True,
                            help_text='Optional description of the attachment',
                            max_length=500,
                        )),
                        ('uploaded_at', models.DateTimeField(
                            auto_now_add=True,
                            help_text='Upload timestamp',
                        )),
                        ('draft', models.ForeignKey(
                            blank=True,
                            help_text='Owning draft (if attached to a draft)',
                            null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='attachments',
                            to='email_communication.emaildraft',
                        )),
                        ('sent_log', models.ForeignKey(
                            blank=True,
                            help_text='Owning sent email log (immutable sent copy)',
                            null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='sent_attachments',
                            to='email_communication.emaillog',
                        )),
                        ('template', models.ForeignKey(
                            blank=True,
                            help_text='Owning template (if attached to a template)',
                            null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='attachments',
                            to='email_communication.emailtemplate',
                        )),
                        ('uploaded_by', models.ForeignKey(
                            blank=True,
                            help_text='User who uploaded this attachment',
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            related_name='uploaded_email_attachments',
                            to=settings.AUTH_USER_MODEL,
                        )),
                    ],
                    options={
                        'verbose_name': 'Email Attachment',
                        'verbose_name_plural': 'Email Attachments',
                        'db_table': 'email_attachment',
                        'ordering': ['uploaded_at'],
                    },
                ),
                migrations.CreateModel(
                    name='EmailLogAttachment',
                    fields=[
                        ('id', models.UUIDField(
                            default=uuid.uuid4, editable=False,
                            primary_key=True, serialize=False,
                        )),
                        ('attachment', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='log_links',
                            to='email_communication.emailattachment',
                            verbose_name='Attachment',
                        )),
                        ('email_log', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='attachment_links',
                            to='email_communication.emaillog',
                            verbose_name='Email Log',
                        )),
                    ],
                    options={
                        'verbose_name': 'Email Log Attachment',
                        'verbose_name_plural': 'Email Log Attachments',
                        'db_table': 'email_log_attachment',
                    },
                ),
                migrations.AddIndex(
                    model_name='emailattachment',
                    index=models.Index(fields=['template'], name='idx_email_att_tmpl'),
                ),
                migrations.AddIndex(
                    model_name='emailattachment',
                    index=models.Index(fields=['draft'], name='idx_email_att_draft'),
                ),
                migrations.AddIndex(
                    model_name='emailattachment',
                    index=models.Index(fields=['sent_log'], name='idx_email_att_log'),
                ),
                migrations.AddIndex(
                    model_name='emaillogattachment',
                    index=models.Index(fields=['email_log'], name='idx_logatt_log'),
                ),
                migrations.AlterUniqueTogether(
                    name='emaillogattachment',
                    unique_together={('email_log', 'attachment')},
                ),
            ],
            # ----------------------------------------------------------------
            # database_operations — actual DDL, idempotent via RunPython.
            # Uses _RunPythonWithToState so the callback sees to_state.apps
            # (which includes EmailAttachment from state_operations above).
            # ----------------------------------------------------------------
            database_operations=[
                _RunPythonWithToState(
                    _create_tables_idempotent,
                    reverse_code=_drop_tables,
                    atomic=False,
                ),
            ],
        ),
    ]
