# Generated by Django 5.2.4 on 2026-05-01 11:08

import authentication.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA-256 hex digest of the 6-digit code — never store plaintext', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=authentication.models._reset_code_expires_at, help_text='Code expires 10 minutes after creation')),
                ('is_used', models.BooleanField(default=False, help_text='True once the password has been successfully reset')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester (for audit)', null=True)),
                ('user', models.ForeignKey(help_text='User who requested the reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Code',
                'verbose_name_plural': 'Password Reset Codes',
                'db_table': 'auth_password_reset_code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used', 'expires_at'], name='auth_passwo_user_id_134a4f_idx')],
            },
        ),
    ]
