# Generated by Django 5.2.4 on 2025-11-19 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_add_validation_type_to_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_answer_value', models.CharField(help_text='The exact answer value that triggers the condition (not encrypted for efficient matching)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependent_question', models.ForeignKey(help_text='The question that appears when the condition is met', on_delete=django.db.models.deletion.CASCADE, related_name='conditional_on', to='surveys.question')),
                ('trigger_question', models.ForeignKey(help_text='The question whose answer triggers this condition', on_delete=django.db.models.deletion.CASCADE, related_name='triggers_for', to='surveys.question')),
            ],
            options={
                'verbose_name': 'Question Condition',
                'verbose_name_plural': 'Question Conditions',
                'db_table': 'surveys_question_condition',
                'indexes': [models.Index(fields=['trigger_question'], name='qcond_trigger_q_idx'), models.Index(fields=['dependent_question'], name='qcond_dependent_q_idx'), models.Index(fields=['trigger_question', 'trigger_answer_value'], name='qcond_trigger_ans_idx')],
                'unique_together': {('trigger_question', 'trigger_answer_value', 'dependent_question')},
            },
        ),
    ]
