# Generated by Django 5.2.4 on 2025-11-19 06:57
# Modified to handle Oracle ORA-00955 error when table already exists

import django.db.models.deletion
import uuid
from django.db import migrations, models, connection


class SafeCreateModel(migrations.CreateModel):
    """
    Custom CreateModel operation that checks if table exists before creating.
    Prevents ORA-00955 errors in Oracle when table already exists.
    """
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Override to check table existence first"""
        table_name = self.name.lower()
        
        # Check if table exists
        with connection.cursor() as cursor:
            table_exists = False
            
            try:
                if connection.vendor == 'oracle':
                    cursor.execute("""
                        SELECT COUNT(*) 
                        FROM user_tables 
                        WHERE UPPER(table_name) = UPPER(:table_name)
                    """, {'table_name': 'surveys_question_condition'})
                    table_exists = cursor.fetchone()[0] > 0
                    
                elif connection.vendor == 'sqlite':
                    cursor.execute("""
                        SELECT COUNT(*) 
                        FROM sqlite_master 
                        WHERE type='table' AND name=?
                    """, ('surveys_question_condition',))
                    table_exists = cursor.fetchone()[0] > 0
                    
                elif connection.vendor in ['postgresql', 'mysql']:
                    cursor.execute("""
                        SELECT COUNT(*) 
                        FROM information_schema.tables 
                        WHERE table_name = %s
                    """, ('surveys_question_condition',))
                    table_exists = cursor.fetchone()[0] > 0
                    
            except Exception as e:
                print(f"Warning: Could not check table existence: {e}")
        
        if table_exists:
            print(f"SUCCESS: Table surveys_question_condition already exists, marking migration as applied")
            # Don't create the table, just update the state
            return
        
        # Table doesn't exist, proceed with normal creation
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
            print(f"SUCCESS: Created table surveys_question_condition")
        except Exception as e:
            if 'ORA-00955' in str(e) or 'already exists' in str(e).lower():
                print(f"INFO: Table already exists (caught during creation), continuing...")
                # Table was created by another process, that's fine
                return
            else:
                # Real error, re-raise
                raise


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_add_validation_type_to_question'),
    ]

    operations = [
        SafeCreateModel(
            name='QuestionCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_answer_value', models.CharField(help_text='The exact answer value that triggers the condition (not encrypted for efficient matching)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependent_question', models.ForeignKey(help_text='The question that appears when the condition is met', on_delete=django.db.models.deletion.CASCADE, related_name='conditional_on', to='surveys.question')),
                ('trigger_question', models.ForeignKey(help_text='The question whose answer triggers this condition', on_delete=django.db.models.deletion.CASCADE, related_name='triggers_for', to='surveys.question')),
            ],
            options={
                'verbose_name': 'Question Condition',
                'verbose_name_plural': 'Question Conditions',
                'db_table': 'surveys_question_condition',
                'indexes': [models.Index(fields=['trigger_question'], name='qcond_trigger_q_idx'), models.Index(fields=['dependent_question'], name='qcond_dependent_q_idx'), models.Index(fields=['trigger_question', 'trigger_answer_value'], name='qcond_trigger_ans_idx')],
                'unique_together': {('trigger_question', 'trigger_answer_value', 'dependent_question')},
            },
        ),
    ]
