# Generated by Django 5.2.4 on 2025-11-20 08:00
# Migration to transition from IP-based to MAC-based device tracking

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_add_question_conditions'),
    ]

    operations = [
        # Add MAC address field as primary device identifier
        migrations.AddField(
            model_name='deviceresponse',
            name='mac_address',
            field=models.CharField(
                blank=True,
                help_text='MAC address of the device (primary device identifier)',
                max_length=17,
                null=True
            ),
        ),
        
        # Update device_fingerprint help text to reflect new MAC-based approach
        migrations.AlterField(
            model_name='deviceresponse',
            name='device_fingerprint',
            field=models.CharField(
                help_text='SHA256 hash of device fingerprint (MAC Address + User-Agent + Screen Resolution + Timezone + Platform)',
                max_length=64
            ),
        ),
        
        # Add index on mac_address for efficient lookups
        migrations.AddIndex(
            model_name='deviceresponse',
            index=models.Index(fields=['mac_address'], name='surveys_device_mac_idx'),
        ),
    ]
