# Generated by Django 5.2.9 on 2026-05-18 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_followups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_attachments',
            field=models.BooleanField(default=False, help_text='Whether respondents can upload attachments with their response'),
        ),
        migrations.AlterField(
            model_name='deviceresponse',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the device (kept for backward compatibility, not used for tracking)', null=True),
        ),
        migrations.CreateModel(
            name='FollowUpMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_data', models.BinaryField(help_text='File content stored as BLOB (max 10MB)')),
                ('original_filename', models.CharField(help_text='Sanitized original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='Validated MIME type', max_length=150)),
                ('description', models.CharField(blank=True, help_text='Optional description of the attachment', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('message', models.ForeignKey(help_text='Parent message (CASCADE deletes attachments when message deleted)', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='surveys.followupmessage')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_followup_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow-Up Message Attachment',
                'verbose_name_plural': 'Follow-Up Message Attachments',
                'db_table': 'surveys_fu_msg_attachment',  # ≤30 chars for Oracle compat
                'ordering': ['uploaded_at'],
                'indexes': [models.Index(fields=['message', 'uploaded_at'], name='followup_att_uploaded_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResponseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_data', models.BinaryField(help_text='File content stored as BLOB (max 10MB)')),
                ('original_filename', models.CharField(help_text='Sanitized original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='Validated MIME type', max_length=150)),
                ('description', models.CharField(blank=True, help_text='Optional description of the attachment', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('response', models.ForeignKey(help_text='Parent response (CASCADE deletes attachments when response deleted)', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='surveys.response')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded (null for anonymous responses)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_response_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response Attachment',
                'verbose_name_plural': 'Response Attachments',
                'db_table': 'surveys_response_attachment',
                'ordering': ['uploaded_at'],
                'indexes': [models.Index(fields=['response', 'uploaded_at'], name='resp_att_uploaded_idx')],
            },
        ),
    ]
