# Generated by Django 5.2.4 on 2026-09-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_add_survey_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytopic',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 for main topics, 1 for sub-topics (see MAX_DEPTH)'),
        ),
        migrations.AlterField(
            model_name='surveytopic',
            name='path',
            field=models.CharField(blank=True, default='', help_text="Materialized path of hex UUIDs, e.g. 'aaaa.bbbb'. Enables subtree queries via path__startswith (an indexable LIKE 'prefix%' on Oracle)", max_length=200),
        ),
    ]
