# Generated by Django 5.2.4 on 2026-09-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('survey_assigned', 'Survey Assigned'), ('survey_completed', 'Survey Completed'), ('survey_shared', 'Survey Shared'), ('survey_updated', 'Survey Updated'), ('survey_deleted', 'Survey Deleted'), ('admin_message', 'Admin Message'), ('system_alert', 'System Alert'), ('user_mention', 'User Mention'), ('group_invitation', 'Group Invitation'), ('response_received', 'Response Received'), ('followup_opened', 'Follow-up Opened'), ('followup_message', 'Follow-up Message'), ('followup_accepted', 'Follow-up Accepted'), ('followup_rejected', 'Follow-up Rejected')], default='admin_message', help_text='Type of notification', max_length=50),
        ),
    ]
